### ISSUE TITLE
"for in" is not highlighted

### ISSUE THREAD

**Issue by arthurk** [jvirtanen/vim-hcl#12]
The "in" keyword is not highlighted in a "for x in" statement:

<img width="553" alt="Screen Shot 2021-03-16 at 4 00 59 PM" src="https://user-images.githubusercontent.com/23406/111275337-03510580-8671-11eb-80c1-94dc82b703e4.png">

**Comment by jvirtanen** [comment]
Good catch, @arthurk! 🔍 I will fix. 👍🏼

**Comment by jvirtanen** [comment]
@arthurk Could you confirm that #13 fixes the issue? 🙂

**Comment by arthurk** [comment]
yes it fixes the issue
